[package]
name = "hello_world_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.8"
ic-cdk = "0.7"
ic-cdk-timers = "0.1" # Feel free to remove this dependency if you don't need timers
ic-cdk-macros = "0.6.10"
serde = "1"